version: '3.8'

services:
  webapp:
    build: ./
    command: ./webapp
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=12345
  db:
    restart: always
    image: postgres:latest
    volumes: 
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=person
      - POSTGRES_PASSWORD=12345
    ports:
      - 5436:5432
volumes:
  db-data: